theme: jekyll-theme-cayman
title: Event-Driven Architecture POC
description: A personal proof of concept (POC) project for a simplified online webstore using an event-driven architecture.

exclude:
  - drawio